# Numpy 套件

In [3]:
a=[1,2,3,4,5]
print(a*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# numpy套件的ndarray型態,提供element-wise的操作

In [4]:
import numpy as np
b=np.array([1,2,3,4,5])
print(b*3)

[ 3  6  9 12 15]


In [5]:
print(type(b))
print(b.ndim)#ndarray的維度
print(b.shape)#ndarray的形狀
print(b.dtype)#ndarray的資料型態


<class 'numpy.ndarray'>
1
(5,)
int32


In [8]:
print(np.zeros(6))#產生1維度的陣列
print(np.zeros((3,6)))#產生2維度的陣列
print(np.zeros((2,3,6)))#產生3維度的陣列

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [9]:
a=np.zeros(16)
print(a)
print(a.shape)
b=a.reshape((4,4))#改變資料的維度維4X4
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


# ndarray的進階操作

In [14]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])#取0 1 2 3 4的位置值

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [25]:
a=np.array([[(0,1,2,3,4,)],[5,6,7,8,9]])
print(a)
b=np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c=np.array(np.arange(0,10).reshape((2,5)))
print(c)

[list([(0, 1, 2, 3, 4)]) list([5, 6, 7, 8, 9])]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


# 二維ndarray取值

In [3]:
import numpy as np
my_2d_array=np.array(np.arange(0,10).reshape((2,5)))
print(my_2d_array)
print(my_2d_array[0,:])#第0列的元素
print(my_2d_array[1,:])#第1列的元素
print(my_2d_array[:,0])#取第0欄的元素
print(my_2d_array[1,1])#取第2列第2欄的元素

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[0 5]
6


# 假設六組 "modern web","Devops","Big Data","cloud","Security" 自我挑戰組 參與人數分別為 56 8 19 14 6 71

In [12]:
import numpy as np
groups=["modern web","Devops","Big Data","cloud","Security" ,"自我挑戰組"]
ironman=[56,8,19,14,6,71]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['modern web' 'Devops' 'Big Data' 'cloud' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


In [13]:
#用人數篩選組別
print(ironman_array >= 10)
print(groups_array[ironman_array >=10])

[ True False  True  True False  True]
['modern web' 'Big Data' 'cloud' '自我挑戰組']


In [16]:
#用組篩選組別
print(groups_array !="自我挑戰組")
print(ironman_array[groups_array !="自我挑戰組"])

[ True  True  True  True  True False]
[56  8 19 14  6]


# ndarray 空值 nan 無限大int

In [20]:
nan_array=np.array([56,8,19,14,6,np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


# 生成10組標準常態(平均為0 標準差為1的常態變數)

In [21]:
normal_samples=np.random.normal(size=10)
print(normal_samples)

[-0.12643397  0.34311015 -1.63982618 -0.53627398  0.0188632  -2.8837636
 -0.53329871  0.47764347  0.99480787 -0.23146043]


# 生成10組介於0~1的隨機變數

In [22]:
uniform_samples=np.random.uniform(size=10)
print(uniform_samples)

[0.62881839 0.51044741 0.32213317 0.46011193 0.9354724  0.49927265
 0.95960374 0.05959032 0.30330906 0.97101244]
